#ifndef WINDOWS_CONSOLE_HPP
#define WINDOWS_CONSOLE_HPP

#include <iostream>

#include <Windows.h>

//Colors for console text
#define WHITE		FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define RED			FOREGROUND_RED|FOREGROUND_INTENSITY
#define ORANGE		FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define GREEN		FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define BLUE		FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define YELLOW		FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define MAGENTA		FOREGROUND_INTENSITY|FOREGROUND_RED|FOREGROUND_BLUE
#define CYAN		FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY

#ifndef CONSOLE_COLOR
#define CONSOLE_COLOR(c) { SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), c); }
#endif

#ifndef PRINT
#define PRINT(stream, color) { CONSOLE_COLOR(color); std::cout<<stream; CONSOLE_COLOR(WHITE); }
#endif

#endif
